name: Optimize resource pack
on: [push, pull_request]
jobs:
  packsquash:
    name: Optimize resource pack
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # A non-shallow repository clone is required
      - name: Run PackSquash
        uses: ComunidadAylas/PackSquash-action@v3
        with:
          path: './Dev Pack/'
          artifact_name: valpack
          options_file: './Dev Pack/options.toml'
          pack_directory: './Dev Pack/'
      - name: Download optimized pack
        uses: actions/download-artifact@v3
        with:
          name: valpack
      - name: Tag and create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: action-v${{ github.run_number }}
          files: pack.zip
